apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
      name: my-app
      namespace: argocd
spec:
    project: default
    source:
      repoURL: https://github.com/Janemils/Helm_Charts.git
      targetRevision: HEAD
      path: /
    destination:
      server: https://kubernetes.default.svc
      namespace: voting
    
    syncPolicy:
      syncOptions:
        - CreateNamespace=true

      automated: 
          selfHeal: true
          prune: true