apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.res.service.name }}
  labels:
    {{- include "charts-voting-res.labels" . | nindent 4 }}
spec:
  type: {{ .Values.res.service.type }}
  ports:
    - port: {{ .Values.res.service.port }}
      targetPort: {{ .Values.res.service.tp }}
      protocol: TCP
      name: http
  selector:
     type: res-dep
